services:
  db:
    image: postgres:13.9
    restart: always
    environment:
      POSTGRES_USER: bookstore-api
      POSTGRES_PASSWORD: admin_9876
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  localstack:
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"